### ISSUE TITLE
2019.05.27 第一次项目讨论

### ISSUE THREAD

**Issue by Jndoi** [hosoneu/his#1]
> 2019.05.27  20:30-22:30
##### 会前准备工作
1. 阅读软件需求规格说明，简要了解涉及到的数据表以及业务流程
2. 通过角色扮演模拟病人看诊流程，角色分配如下：
     - 挂号收费员（张钧贺）
     - 门诊医生（曾秋阳）
     - 医技医生（张君治）
     - 药房操作员（王一宁）
     - 财务管理员（夏非凡）
     - 医院管理员（张钧贺）
     - 病人（志愿者：王贵平）
3. 简要了解vue、bootstrap、git等可能用到的技术
4. 简要讨论项目开发阶段，确定下一阶段的工作
##### 会议主要内容
1. 设计数据库（确定有哪些表）
2. 角色扮演模拟看诊流程
3. 确定下一阶段的工作
4. 拟定每周三次项目会议用于整合项目进度
##### 下一阶段工作
1. 截止时间：2019.6.3
2. 任务：
      - 数据库设计（曾秋阳、张钧贺）
      - 原型设计（王一宁、夏非凡、张君治）
      - ps:数据库设计完协助完成原型设计

**Comment by T0UGH** [comment]
还是阳哥🐏强啊
