### ISSUE TITLE
2019.06.17 git使用建议和develop分支的引入

### ISSUE THREAD

**Issue by T0UGH** [hosoneu/his#13]
大家好，对于git分支，现改变策略
#### 1  新建develop分支，作为开发主分支
1. 当大家需要开发新特性时，从develop分支拉取新分支
2.  新特性开发完成后，大家提交代码到与本地分支名相同的远程分支，并向develop分支发出合并请求，张钧贺负责合并，develop的合并要非常及时，以免影响后续开发
3. 对新合并的develop分支，要经过一定的验证，验证完成没有问题，则合并到master上，若出现问题，则从develop分支上拉取新的fix分支，修改bug
#### 2 git使用建议
1. 大家没有养成commit习惯，以张君治为例，他整个特性开发就只有一次commit，这样是不对的，对于提交粒度问题，大家可以参看[这里](https://github.com/hosoneu/his_Vue/commits/master)。基本上每次修改完一个文件都可以提交一次，每次提交只做一件事，比如，我这次提交就完成这一个类，那就commit这一个类，切勿全部提交。
2. 每天开发完成后，大家要记得把今天的成果提到你自己的远程分支上，做代码备份，不然万一电脑坏了就全没了。
3. 大家的分支名不要起成自己的名字，因为每次特性分支完成合并，都会被删除，应起为要开发的特性的名称。
4. 对于每个特性分支要完成什么功能，粒度还是太粗，粒度粗带来的后果是，很多代码冲突会留到最后，所以对于本次合并，我的预估是不乐观的，会很难合并，因为粒度太粗。
5. 基于上面的问题，请大家在开发前端的时候注意，对于大家是否会接受这些建议，我也不抱乐观估计。

**Comment by Mike4Ellis** [comment]
合并请求是向develop，不是向master
